# Generated by Django 5.1 on 2024-11-06 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_userloginhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date_added',
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
